#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
#    username: root
#    password: 123456
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: MYSQL
#    show-sql: true
#    ddl-auto: update
#    properties:
#      hibernate.id.new_generator_mappings: true
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: false
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#server:
#  port: 13500
#logging:
#  level:
#    ROOT: INFO
#server:
#  servlet:
#    context-path: /context_path